# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    configs:
        game:
            toolbar: 'toolbarGame'
            height: '500px'
            extraPlugins: "youtube"
        comment:
            toolbar: 'toolbarComment'
            height: '150px'

    toolbars:
        configs:
            toolbarGame: [
                [
                        'Bold',
                        'Italic',
                        'Underline',
                        'Strike',
                        '-',
                        'RemoveFormat',
                        '-',
                        'Cut',
                        'Copy',
                        'Paste',
                        'PasteText',
                        'PasteFromWord',
                        '-',
                        'Undo',
                        'Redo',
                        '-',
                        'Font',
                        'FontSize',
                        'TextColor',
                        'BGColor'
                ],
                [
                        'NumberedList',
                        'BulletedList',
                        '-',
                        'Outdent',
                        'Indent',
                        '-',
                        'Blockquote',
                        '-',
                        'Link',
                        'Youtube',
                        '-',
                        'JustifyLeft',
                        'JustifyCenter',
                        'JustifyRight',
                        'JustifyBlock',
                        '-',
                        'Image',
                        'Table',
                        'HorizontalRule',
                        'SpecialChar'
                ],

            ]
            toolbarComment: [
                [
                        'Bold',
                        'Italic',
                        'Underline',
                        'Strike',
                        '-',
                        'RemoveFormat',
                        '-',
                        'Undo',
                        'Redo',

                ],
                [
                        'NumberedList',
                        'BulletedList',
                        '-',
                        'Blockquote',
                        'embed',
                        '-',
                        'JustifyLeft',
                        'JustifyCenter',
                        'JustifyRight',
                        'JustifyBlock',
                        '-',
                        'Image',
                        'SpecialChar'
                ],

            ]



twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
